name: Test

on:
  push:
    branches: [ feature ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Display dotnet version
        run: dotnet --version 
      - name: Install dependencies
        run: dotnet restore lr2/lr2.sln
      - name: Build
        run: dotnet build lr2/lr2.scproj
      - name: Test with the dotnet CLI
        run: dotnet test --logger trx lr2.Test/lr2.Test.scproj